### ISSUE TITLE
LLVM safestack miscompile issue

### ISSUE THREAD

**Issue by laanwj** [NuxiNL/cloudabi-ports#30]
I had crashes with SafeStack in #28. After upgrading to the 4.0-devel version I'm seeing a more suble problem: some of the bitcoin tests ( `key_tests/key_test1`) fail. I narrowed this down to RFC6979 nonce generation in the secp256k1 library.

To be precise, this function gets compiled wrongly: https://github.com/bitcoin-core/secp256k1/blob/master/src/hash_impl.h#L235 . This results in invalid deterministic signatures.

This was a bit of a quantum bug - when adding fprintf statements, sometimes the bug went into hiding. However after disabling safe-stack with `-fno-sanitize=safe-stack` the problem goes away and all the tests pass!

I haven't checked the assembly to see where it exactly goes wrong (can a CloudABI program be single-stepped?) but anyhow, just wanted to report it. I think it's a bug in clang and it may very well have been solved already in SVN.

(I don't currently have enough disk space on my FreeBSD dev VM to build the ports from scratch, that's why I've been stuck with binaries)

**Comment by EdSchouten** [comment]
That's interesting. Can you come up with a minimised testcase? As in, a simple C file that is supposed to print A, but prints B instead. If so, I can also spend some time to root-cause and report upstream.

As far as I know, you should be able to use GDB and attach to CloudABI processes, but be sure to install GDB from Ports, as the one in the base system is pretty much useless. It's the last version that was GPLv2 licensed, so it only supports DWARFv2. Clang nowadays emits DWARFv4, so that's why you need a recent GDB.

What is annoying about GDB: right now you can only attach to running CloudABI processes or start executables that use `int main()`, not `void program_main()`. We should somehow teach `cloudabi-run` to know how to spawn processes with the debugger attached.

(By the way, in the meantime I'm looking into porting ZeroMQ!)

**Comment by laanwj** [comment]
I'm working on getting the secp256k1 tests to run. That'd already be a step closer to the source, at least.

> (By the way, in the meantime I'm looking into porting ZeroMQ!)

Awesome! Yes that's one of the libraries that would be useful for Bitcoin Core. And generally seems a pretty important library for modern-day applications.

We're going to switch away from Berkeley DB (as it's overkill for what we're doing, and questionable license-wise) so I'd say don't bother with that one.

**Comment by laanwj** [comment]
Here's a self-contained repro case: [issue30.tar.gz](https://github.com/NuxiNL/cloudabi-ports/files/816635/issue30.tar.gz). It is a simple test that compares `rfc6979_hmac_sha256` output with predefined inputs against expected values.

Archive contains:

- `compile.sh` compile script (rebuilds `tests_fail` `tests_ok`)
- `run.sh` run script (runs `tests_fail` `tests_ok`)
- `tests.c` source code
- `tests.yaml` cloudabi config
- `tests_fail` executable with safe-stack, that fails
- `tests_ok` executable without safe-stack, that succeeds

What I've figured out:

- `-fno-sanitize=safe-stack` makes the test pass: clear
- `-O0` or `-O1` makes the test pass, `-O2` or higher makes it fail. Haven't tried out which specific (set of) compilation flag exposes the issue, but it may give more insight if the cause is safe-stack combined with a certain optimization.

**Comment by EdSchouten** [comment]
Filed a bug report upstream: https://bugs.llvm.org//show_bug.cgi?id=32143

**Comment by laanwj** [comment]
@EdSchouten thanks!
