### ISSUE TITLE
aarch64-unknown-cloudabi-freetype fails to build on Ubuntu 15.10

### ISSUE THREAD

**Issue by moreati** [NuxiNL/cloudabi-ports#5]
I'm not sure if this is relevant or noteworthy. Please feel free to e.g. close it as wontfix.

On MacbookPro11,2 running Ubuntu 15.10 the following error occurs while building freetype

```
checking for x86_64-pc-linux-gnu-gcc... /usr/bin/cc
checking for x86_64-pc-linux-gnu-gcc... (cached) /usr/bin/cc
checking for x86_64-pc-linux-gnu-gcc... (cached) /usr/bin/cc
checking for suffix of native executables... gcc-5.real: error trying to exec 'as': execvp: No such file or directory
```

It appears that `cloudabi-ports/src/config.py` unconditionally supplies `CC_FOR_BUILD=/usr/bin/cc`. On FreeBSD 10.2 this is clang 3.4, on Debian & Ubuntu it's gcc. Would you like a PR making this more like the HOST_CC and HOST_CXX platform dependent (like PERL)?

For reference I'm using the following locally, while I learn the ins and outs of cloudabi-ports

``` diff
diff --git a/src/config.py b/src/config.py
index 6d0f901..709d798 100644
--- a/src/config.py
+++ b/src/config.py
@@ -25,2 +25,4 @@ FALLBACK_MIRRORS = {'https://nuxi.nl/distfiles/third_party/'}
-HOST_CC = '/usr/bin/cc'
-HOST_CXX = '/usr/bin/c++'
+HOST_CC = ('/usr/bin/clang-3.7' if platform.system() == 'Linux' else
+           '/usr/bin/cc')
+HOST_CXX = ('/usr/bin/clang++-3.7' if platform.system() == 'Linux' else
+            '/usr/bin/c++')
```

**Comment by EdSchouten** [comment]
I remember I also ran into this issue right before Christmas and as far as I know, the problem is as follows. I tried to have the build process almost entirely separated from the operating system you build on (which is why we build Coreutils, etc). Now, the problem is that GCC requires that the PATH is set in such a way that it can find its as/ld executables. Clang doesn't care, because it doesn't use PATH -- it looks at the /bin/ directory relative to its own location.

Now the question is: how do we want to fix this? We can decide to pollute PATH on Linux so that GCC still works like before, or we can use Clang on Linux as well. Both solutions are fine by me. Which solution do you prefer? :-)

**Comment by moreati** [comment]
> Which solution do you prefer? :-)

Clearly you understand this better. I have no preference for one compiler vs the other, a weak preference for not doing PATH trickery. So +0 clang, but +1 defer to your judgement.
